redis:
  image: redis:alpine
  restart: always
  hostname: redis
  ports:
    - "6379:6379"
  volumes:
    - /var/lib/redis/data:/data

app:
  build: .
  restart: always
  hostname: products
  ports:
    - "5000:5000"
  links:
    - redis
